resource_prefix          = "cmtr-f5n7jzgb-mod9"
location                 = "East US"
resource_group           = "cmtr-f5n7jzgb-mod9-rg"
vnet_name                = "cmtr-f5n7jzgb-mod9-vnet"
vnet_address_space       = "10.0.0.0/16"
aks_subnet_name          = "aks-snet"
aks_subnet_address_space = "10.0.0.0/24"
aks_loadbalancer_ip      = "51.8.21.37"